#!/usr/bin/env bash


realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

startingDir=$PWD

for dir in `find . -name .git -type d -exec dirname {} \;`; do
    gitdir=`realpath "$dir"`
    cd "$gitdir"
    git ls-remote --heads &>/dev/null
    if [ $? -eq 0 ]; then
        echo "Running in: $gitdir"
        read -p "Are you sure? " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            git reset HEAD --hard   
        fi
    fi
    cd "$startingDir"
done